CURDusingEF/Models/AccountModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;


namespace CURDusingEF.Models
{
  
    [Table("Booking.Room")]
    public class AccountModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RoomId { get; set; }

        public string RoomNumber { get; set; }

        public string RoomImage { get; set; }

        public decimal RoomPrice { get; set; }

        public string RoomType { get; set; }

        public int RoomCapacity { get; set; }

        public string RoomDescription { get; set; }

        public string IsActive { get; set; }




    }

    [Table("contact")]
    public class Contact
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        

        public int id { get; set; }
        public string fullName { get; set; }

        public string Email { get; set; }

        public Int64 Phoneno { get; set; }

        public string Subject { get; set; } 

        public string Message {  get; set; }
    }

    
}

CURDusingEF/Models/BookingModel.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CURDusingEF.Models
{
    [Table("CustomerRoombooking")]
    public class BookingModel
    {

            [Key]
            public string RoomNumber { get; set; }

            public string CustomerName { get; set; }

            public Int64 MobileNo { get; set; }

            public int Adult { get; set; }

            public int ChildrenCount { get; set; }

            public string RoomType { get; set; }

            public Int64 AadharNo { get; set; }

            public DateTime CheckIn { get; set; }
            public DateTime CheckOut { get; set; }


    }
}

CURDusingEF/Models/DatabaseContext.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
namespace CURDusingEF.Models
{
    public class DatabaseContext : DbContext
    {
        public DatabaseContext() { }


        public DatabaseContext(DbContextOptions<DatabaseContext> options) : base(options) { }

        public virtual DbSet<AccountModel> AccountModel { get; set; }

        public virtual DbSet<BookingModel> BookingModel { get; set; }

        public virtual DbSet<Contact> Contact { get; set; }
    }
}

CURDusingEF/Models/ErrorViewModel.cs
namespace CURDusingEF.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CURDusingEF/Controllers/AccountController.cs
using CURDusingEF.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Data.SqlClient;

namespace CURDusingEF.Controllers
{
    
    public class AccountController : Controller
    {
        public readonly DatabaseContext _context;
        public AccountController(DatabaseContext context) {
            _context = context;
        }

       
        public IActionResult Home()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Contact()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Contact(Contact obj)
        {
            if (obj == null)
            {

            }
            else
            {
                if (ModelState.IsValid)
                {
                    _context.Contact.Add(obj);
                    int x = _context.SaveChanges();
                    if (x > 0)
                    {
                        return RedirectToAction("Home", "Account");
                    }

                }
            }
            return View();
        }

        public IActionResult Services()
        {
            return View();
        }

      
       
    }
    
}

CURDusingEF/Controllers/AdminController.cs
using CURDusingEF.Models;
using Microsoft.AspNetCore.Mvc;

namespace CURDusingEF.Controllers
{
    public class AdminController : Controller
    {
        public readonly DatabaseContext _context;
        public AdminController(DatabaseContext context)
        {
            _context = context;
        }
        public IActionResult Admin()
        {
            return View();
        }


        [HttpGet]
        public IActionResult AddRoom()
        {

            return View();
        }


        [HttpPost]
        public IActionResult AddRoom(AccountModel obj)
        {
            if (obj == null)
            {

            }
            else
            {
                if(ModelState.IsValid)
                {
                    _context.Add(obj);
                    int x = _context.SaveChanges();
                    if (x > 0)
                    {
                        return RedirectToAction("Index", "Room");
                    }
                }
            }
            return View();
        }
        [HttpGet]
        public IActionResult Edit(int? RoomId)
        {
            var res = _context.AccountModel.Find(RoomId);

            return View(res);
        }
        [HttpPost]
        public IActionResult Edit(AccountModel obj, int? RoomId)
        {
            if (obj == null)
            {

            }
            else
            {
                if (ModelState.IsValid)
                {
                    _context.Update(obj);
                    int x = _context.SaveChanges();
                    if (x > 0)
                    {
                        return RedirectToAction("ViewRoom", "Admin");
                    }
                }
            }
            return View();
        }

        public IActionResult ViewRoom() 
        {
            var res = from s in _context.AccountModel select s;
            return View(res.ToList());
        }

        public  new IActionResult Request()
        {
            var res = from s in _context.BookingModel select s;
            return View(res.ToList());
            
        }

    }
}

CURDusingEF/Controllers/BookingController.cs
using CURDusingEF.Models;
using Microsoft.AspNetCore.Mvc;

namespace CURDusingEF.Controllers
{
    public class BookingController : Controller
    {

        public readonly DatabaseContext _context;
        public BookingController(DatabaseContext context)
        {
            _context = context;
        }


        [HttpGet]
        public IActionResult roombook()
        {

            return View();
        }
        [HttpPost]
        public IActionResult roombook(BookingModel obj)
        {
            if (obj == null)
            {

            }
            else
            {
                if(ModelState.IsValid)
                {
                    _context.Add(obj);
                    int x = _context.SaveChanges(); 
                    if (x > 0)
                    {
                        return RedirectToAction("Home", "Account");
                    }

                }
            }
            return View();
        }
    }
}

CURDusingEF/Controllers/HomeController.cs
using CURDusingEF.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CURDusingEF.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CURDusingEF/Controllers/RoomController.cs
using CURDusingEF.Models;
using Microsoft.AspNetCore.Mvc;

namespace CURDusingEF.Controllers
{
    public class RoomController : Controller
    {
        public readonly DatabaseContext _context;
        public RoomController(DatabaseContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var res = from s in _context.AccountModel select s;

            return View(res.ToList());
        }
    }
}

CURDusingEF/Views/Admin/AddRoom.cshtml
@model AccountModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRoom</title>
    <meta name="viewport" content="width=device-width" />
    <title>Book</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <style type="text/css">
        h2 {
            font-family: 'Open Sans', sans-serif;
            font-size: 40px;
            font-weight: 600;
            color: Black;
            margin-top: 2%;
            text-align: center;
            text-transform: uppercase;
            letter-spacing: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <h2>Add Room</h2>
            
            <div class="form-group">
                <label for="Id" class="col-sm-3 control-label">Room Number</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="firstName" class="col-sm-3 control-label">Room Image</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomImage, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomImage, "", new { @class = "text-danger" })<br />
                </div>
            </div>
            <div class="form-group">
                <label for="phoneNumber" class="col-sm-3 control-label">Room Price </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomPrice, "", new { @class = "text-danger" })<br />

                </div>
            </div>


            

            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Room Type </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomType, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomType, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="col-sm-3 control-label">Room Capacity</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomCapacity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomCapacity, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Room Description</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomDescription, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomDescription, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Is Active</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.IsActive, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })<br />
                    <br />
                </div>
            </div>


            
            <input type="submit" value="Add Room" name="submit" class="btn btn-primary btn-block" />

        }
    </div>
</body>
</html>

CURDusingEF/Views/Admin/Admin.cshtml
@{
    ViewData["Title"] = "Admin";
    Layout = "~/Views/Shared/Master_Layout.cshtml";
}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
<style>
    body {
        background-image: url("https://images.pexels.com/photos/258154/pexels-photo-258154.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1");
        background-size: cover;
    }

    div.container {
        margin: auto;
        padding-right: 5px;
        width: 30rem;
        position: absolute;
    }
</style>

<html>
<body>

</body>
</html>

CURDusingEF/Views/Admin/Edit.cshtml
@model AccountModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AddRoom</title>
    <meta name="viewport" content="width=device-width" />
    <title>Book</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <style type="text/css">
        h2 {
            font-family: 'Open Sans', sans-serif;
            font-size: 40px;
            font-weight: 600;
            color: Black;
            margin-top: 2%;
            text-align: center;
            text-transform: uppercase;
            letter-spacing: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <h2>Add Room</h2>

            <div class="form-group">
                <label for="Id" class="col-sm-3 control-label">Room Number</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="firstName" class="col-sm-3 control-label">Room Image</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomImage, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomImage, "", new { @class = "text-danger" })<br />
                </div>
            </div>
            <div class="form-group">
                <label for="phoneNumber" class="col-sm-3 control-label">Room Price </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomPrice, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomPrice, "", new { @class = "text-danger" })<br />

                </div>
            </div>




            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Room Type </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomType, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomType, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="col-sm-3 control-label">Room Capacity</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomCapacity, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomCapacity, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Room Description</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomDescription, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomDescription, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Is Active</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.IsActive, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })<br />
                    <br />
                </div>
            </div>



            <input type="submit" value="Add Room" name="submit" class="btn btn-primary btn-block" />

        }
    </div>
</body>
</html>

CURDusingEF/Views/Admin/ViewRoom.cshtml
@model IEnumerable<CURDusingEF.Models.AccountModel>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewRoom</title>
    <meta name="viewport" content="width=device-width" />
    <title>Room</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">RoomId</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">RoomImage</th>

                <th scope="col">RoomPrice</th>

                <th scope="col">RoomType</th>
                <th scope="col">RoomCapacity</th>
                <th scope="col">RoomDescription</th>
                <th scope="col">IsActive</th>
                <th scope="col">Edit</th>


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.RoomId</td>
                    <td>@item.RoomNumber</td>
                    <td>@item.RoomImage</td>
                    <td>@item.RoomPrice</td>

                    <td>@item.RoomType</td>
                    <td>@item.RoomCapacity</td>
                    <td>@item.RoomDescription</td>
                    <td>@item.IsActive</td>
                    <td>@Html.ActionLink("Edit", "Edit", "Admin", new{RoomId = item.RoomId})</td>

                </tr>
            }

        </tbody>
    </table>
</body>
</html>

CURDusingEF/Views/Admin/request.cshtml
@model IEnumerable<CURDusingEF.Models.BookingModel>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Request</title>
    <meta name="viewport" content="width=device-width" />
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>
    <table class="table">
        <thead>
            <tr>
                
                <th scope="col">Room Number</th>
                <th scope="col">Customer Name</th>
                <th scope="col">Mobile No</th>
                <th scope="col">Adult</th>
                <th scope="col">Children Count</th>
                <th scope="col">RoomType</th>
                <th scope="col">Aadhar No</th>
                <th scope="col">Check In</th>
                <th scope="col">Check Out</th>
                


            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                  
                    <td>@item.RoomNumber</td>
                    <td>@item.CustomerName</td>
                    <td>@item.MobileNo</td>
                    <td>@item.Adult</td>
                    <td>@item.ChildrenCount</td>
                    <td>@item.RoomType</td>
                    <td>@item.AadharNo</td>
                    <td>@item.CheckIn</td>
                    <td>@item.CheckOut</td>
                    

                </tr>
            }

        </tbody>
    </table>
</body>
</html>

CURDusingEF/Views/Booking/roombook.cshtml
@model BookingModel
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Book</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>


    <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-2.1.3.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validate/1.16.0/jquery.validate.min.js"></script>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery.validation.unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>

    <style type="text/css">
        h2 {
            font-family: 'Open Sans', sans-serif;
            font-size: 40px;
            font-weight: 600;
            color: burlywood;
            margin-top: 2%;
            text-align: center;
            text-transform: uppercase;
            letter-spacing: 4px;
        }
    </style>
</head>
<body>
    <div class="container">
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <h2>Room Booking</h2>
            <div class="form-group">
                <label for="Id" class="col-sm-3 control-label">Room Number</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomNumber, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomNumber, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="firstName" class="col-sm-3 control-label">Customer Name</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.CustomerName, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })<br />
                </div>
            </div>
            <div class="form-group">
                <label for="phoneNumber" class="col-sm-3 control-label">Mobile Number </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.MobileNo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })<br />

                </div>
            </div>
            

            <div class="form-group">
                <label for="lastName" class="col-sm-3 control-label">Adult Count</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.Adult, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Adult, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-sm-3 control-label">Children Count </label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.ChildrenCount, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.ChildrenCount, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="col-sm-3 control-label">Room Type</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.RoomType, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.RoomType, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Addhar No</label>
                <div class="col-sm-9">
                    @Html.TextBoxFor(model => model.AadharNo, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.AadharNo, "", new { @class = "text-danger" })<br />
                </div>
            </div>

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Check In</label>
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.CheckIn, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CheckIn, "", new { @class = "text-danger" })<br />
                    <br />
                </div>
            </div>
            

            <div class="form-group">
                <label for="aadharno" class="col-sm-3 control-label">Check Out</label>
                <div class="col-sm-9">
                    @Html.EditorFor(model => model.CheckOut, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CheckOut, "", new { @class = "text-danger" })<br />
                    <br />
                </div>
            </div>
            <input type="submit" value="Book Room" name="submit" class="btn btn-primary btn-block" />

        }
    </div>
</body>
</html>

CURDusingEF/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CURDusingEF/Views/Room/Index.cshtml
@model IEnumerable<CURDusingEF.Models.AccountModel>
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Room</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</head>

<body>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">RoomId</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">RoomImage</th>
                                
                <th scope="col">RoomPrice</th>
                
                <th scope="col">RoomType</th>
                <th scope="col">RoomCapacity</th>
                <th scope="col">RoomDescription</th>
                <th scope="col">IsActive</th>
                <th scope="col">Book Now</th>
                
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.RoomId</td>
                    <td>@item.RoomNumber</td>
                    <td>@item.RoomImage</td>
                    <td>@item.RoomPrice</td>
                    
                    <td>@item.RoomType</td>
                    <td>@item.RoomCapacity</td>
                    <td>@item.RoomDescription</td>
                    <td>@item.IsActive</td>   
                    <td>@Html.ActionLink("Book Now","Booking","Booking")</td>
                    
                </tr>
            }
            
        </tbody>
    </table>




</body>
</html>